// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeAlert(arg1, arg2) {
  return window['go']['server']['App']['AcknowledgeAlert'](arg1, arg2);
}

export function AddDefaultHeuristicRules() {
  return window['go']['server']['App']['AddDefaultHeuristicRules']();
}

export function CheckPermission() {
  return window['go']['server']['App']['CheckPermission']();
}

export function ClearAllAlertRules() {
  return window['go']['server']['App']['ClearAllAlertRules']();
}

export function ClearAllAlerts() {
  return window['go']['server']['App']['ClearAllAlerts']();
}

export function ClearAllData() {
  return window['go']['server']['App']['ClearAllData']();
}

export function ClearProcessStats() {
  return window['go']['server']['App']['ClearProcessStats']();
}

export function CreateAlertRule(arg1) {
  return window['go']['server']['App']['CreateAlertRule'](arg1);
}

export function DeleteAlertLog(arg1) {
  return window['go']['server']['App']['DeleteAlertLog'](arg1);
}

export function DeleteAlertRule(arg1) {
  return window['go']['server']['App']['DeleteAlertRule'](arg1);
}

export function ExportPCAP(arg1, arg2) {
  return window['go']['server']['App']['ExportPCAP'](arg1, arg2);
}

export function GetAlertRule(arg1) {
  return window['go']['server']['App']['GetAlertRule'](arg1);
}

export function GetAlertStats() {
  return window['go']['server']['App']['GetAlertStats']();
}

export function GetAppClassificationAccuracy() {
  return window['go']['server']['App']['GetAppClassificationAccuracy']();
}

export function GetAppClassificationStats(arg1, arg2) {
  return window['go']['server']['App']['GetAppClassificationStats'](arg1, arg2);
}

export function GetClassificationAccuracy() {
  return window['go']['server']['App']['GetClassificationAccuracy']();
}

export function GetConfig() {
  return window['go']['server']['App']['GetConfig']();
}

export function GetCurrentInterface() {
  return window['go']['server']['App']['GetCurrentInterface']();
}

export function GetDashboardStats() {
  return window['go']['server']['App']['GetDashboardStats']();
}

export function GetInterfaces() {
  return window['go']['server']['App']['GetInterfaces']();
}

export function GetLibraryVersion() {
  return window['go']['server']['App']['GetLibraryVersion']();
}

export function GetLimits() {
  return window['go']['server']['App']['GetLimits']();
}

export function GetMaltrailEvents(arg1, arg2, arg3, arg4) {
  return window['go']['server']['App']['GetMaltrailEvents'](arg1, arg2, arg3, arg4);
}

export function GetMetrics() {
  return window['go']['server']['App']['GetMetrics']();
}

export function GetNpcapDownloadURL() {
  return window['go']['server']['App']['GetNpcapDownloadURL']();
}

export function GetProcessStats(arg1, arg2) {
  return window['go']['server']['App']['GetProcessStats'](arg1, arg2);
}

export function GetProtocolDistribution() {
  return window['go']['server']['App']['GetProtocolDistribution']();
}

export function GetRawPackets(arg1) {
  return window['go']['server']['App']['GetRawPackets'](arg1);
}

export function GetSessions(arg1, arg2) {
  return window['go']['server']['App']['GetSessions'](arg1, arg2);
}

export function GetSnapshot(arg1, arg2) {
  return window['go']['server']['App']['GetSnapshot'](arg1, arg2);
}

export function GetStorageStats() {
  return window['go']['server']['App']['GetStorageStats']();
}

export function GetTopProcessesByTraffic(arg1) {
  return window['go']['server']['App']['GetTopProcessesByTraffic'](arg1);
}

export function ImportMaltrailTrails(arg1, arg2, arg3, arg4) {
  return window['go']['server']['App']['ImportMaltrailTrails'](arg1, arg2, arg3, arg4);
}

export function InsertTestMaltrailEvent() {
  return window['go']['server']['App']['InsertTestMaltrailEvent']();
}

export function IsCapturing() {
  return window['go']['server']['App']['IsCapturing']();
}

export function IsPaused() {
  return window['go']['server']['App']['IsPaused']();
}

export function ListIntelCategories() {
  return window['go']['server']['App']['ListIntelCategories']();
}

export function PauseCapture() {
  return window['go']['server']['App']['PauseCapture']();
}

export function QueryAlertLogs(arg1) {
  return window['go']['server']['App']['QueryAlertLogs'](arg1);
}

export function QueryAlertRules(arg1) {
  return window['go']['server']['App']['QueryAlertRules'](arg1);
}

export function QuerySessionFlows(arg1) {
  return window['go']['server']['App']['QuerySessionFlows'](arg1);
}

export function QuerySessions(arg1) {
  return window['go']['server']['App']['QuerySessions'](arg1);
}

export function RefreshReplayDatabase() {
  return window['go']['server']['App']['RefreshReplayDatabase']();
}

export function ResumeCapture() {
  return window['go']['server']['App']['ResumeCapture']();
}

export function RunProcessScript(arg1) {
  return window['go']['server']['App']['RunProcessScript'](arg1);
}

export function SetIntelCategoryEnabled(arg1, arg2) {
  return window['go']['server']['App']['SetIntelCategoryEnabled'](arg1, arg2);
}

export function StartAppClassificationScheduler(arg1, arg2) {
  return window['go']['server']['App']['StartAppClassificationScheduler'](arg1, arg2);
}

export function StartCapture(arg1) {
  return window['go']['server']['App']['StartCapture'](arg1);
}

export function StartCaptureWithDB(arg1) {
  return window['go']['server']['App']['StartCaptureWithDB'](arg1);
}

export function StopCapture() {
  return window['go']['server']['App']['StopCapture']();
}

export function SyncIntelFromMaltrail(arg1, arg2) {
  return window['go']['server']['App']['SyncIntelFromMaltrail'](arg1, arg2);
}

export function UpdateAlertRule(arg1) {
  return window['go']['server']['App']['UpdateAlertRule'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['server']['App']['UpdateConfig'](arg1);
}

export function UpdateLimits(arg1) {
  return window['go']['server']['App']['UpdateLimits'](arg1);
}

export function VacuumStorage() {
  return window['go']['server']['App']['VacuumStorage']();
}
